---
# We need to include our RHSM entitlements from the secrets repo to subscribe
# RHEL systems during post-install.
- name: Include RHSM entitlement credentials
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ secrets_path }}/entitlements.yml"
    - roles/common/vars/empty.yml
  no_log: true
  tags:
    - always

- name: Upload index.html template
  template:
    src: "httpd/index.html"
    dest: "/var/www/html/"
    owner: root
    group: root
    mode: 0644
  tags:
    - httpd

- name: Upload kickstarts and preseeds.
  template:
    src: "kickstarts/{{ item }}"
    dest: "{{ ks_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644 
  with_items: "{{ kickstarts }}"
  tags:
    - kickstarts

- name: Upload snippets
  template:
    src: "snippets/{{ item }}"
    dest: "/var/lib/cobbler/snippets/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ snippets }}"
  tags:
    - snippets

- name: Upload scripts.
  template:
    src: "scripts/{{ item }}"
    dest: "/var/lib/cobbler/scripts/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ scripts }}"
  tags:
    - scripts

- name: Upload triggers.
  template:
    src: "triggers/{{ item }}"
    dest: "/var/lib/cobbler/triggers/{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items: "{{ triggers }}"
  tags:
    - triggers

- name: Create /root/bin
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - utils

- name: Upload utilities for convenience.
  template:
    src: "utils/{{ item }}"
    dest: "/root/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ utils }}"
  tags:
    - utils
