---
- name: Enable Cobbler 3 Stream on RHEL8
  command: "dnf module enable cobbler:3"
  when: ansible_distribution_major_version|int >= 8

- name: Install cobbler
  yum:
    name: "{{ cobbler_package }}"
    state: latest
  register: install_cobbler

- name: Install extra cobbler packages
  yum:
    name: "{{ cobbler_extra_packages|list }}"
    state: latest
  when: cobbler_extra_packages|length > 0

# configure red hat specific things
- import_tasks: setup-redhat.yml
  when: ansible_distribution in ('RedHat', 'CentOS')
