---
- name: Fail on zypper systems if paddles_containerized is set
  fail:
    msg: "'paddles_containerized' is not yet supported on zypper systems"
  when: paddles_containerized

- name: Include package type specific vars.
  include_vars: "zypper_systems.yml"
  tags:
    - always

- name: Install packages via zypper
  zypper:
    name: "{{ paddles_extra_packages|list }}"
    state: latest
    update_cache: yes
  tags:
    - packages

- name: Enable and start database
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Enable and start supervisor
  service:
    name: supervisord
    state: started
    enabled: yes

- name: Disable ProtectHome=true for supervisor
  lineinfile:
    path: "/etc/systemd/system/multi-user.target.wants/supervisord.service"
    state: present
    regexp: "^(ProtectHome=true.*)"
    line: '#\1'
    backrefs: yes

- name: Reload supervisor
  service:
    name: supervisord
    state: restarted
    daemon_reload: yes

- name: Setup hba_conf
  lineinfile:
    path: "/var/lib/pgsql/data/pg_hba.conf"
    insertafter: "^#\\s+TYPE\\s+DATABASE\\s+USER\\s+ADDRESS\\s+METHOD.*"
    line: "host    paddles         {{ paddles_user }}        ::1/128             trust"

- name: Reload database
  service:
    name: postgresql
    state: reloaded
