---
- name: Include secrets
  include_vars: "{{ item }}"
  no_log: true
  with_first_found:
    - "{{ secrets_path | mandatory }}/nameserver.yml"
    - empty.yml
  tags:
    - always

# Install and update system packages
- import_tasks: packages.yml
  tags:
    - packages

- name: Enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes
  tags:
    - always

# DDNS updates fail to create or edit jnl files without this
- name: Ensure permissions set for "{{ named_conf_zones_path }}"
  file:
    path: "{{ named_conf_zones_path }}"
    mode: '0700'
    state: directory
    owner: named
    group: named
  tags:
    - always

# Configure firewalld
- import_tasks: firewall.yml
  tags:
    - firewall

# Configure BIND
- import_tasks: config.yml
  tags:
    - config

# Compile and write zone files
- import_tasks: records.yml
  tags:
    - records
  when: (named_conf_slave is undefined) or
        (named_conf_slave is defined and named_conf_slave == false)

# The tasks below are last so the grep output is near the end of the play
- set_fact:
    have_collisions: true
  when:
    - (named_conf_slave is undefined) or (named_conf_slave is defined and named_conf_slave == false)
    - nameserver_collisions_grep is defined and nameserver_collisions_grep.stdout | length > 0
  tags:
    - records

- name: Print IP collisions
  debug:
    msg:
      - "WARNING: The following IP addresses have multiple records in DNS.  Check for IP collisions!"
      - "Either re-run this playbook with '-vvv' or `grep -r -w {{ inventory_dir }}/{{ lab_name }} {{ inventory_dir }}/group_vars/nameserver.yml` for the IPs below."
      - "{{ nameserver_collisions_grep.stdout_lines }}"
  when: have_collisions is defined and have_collisions|bool
  tags:
    - records

- name: grep duplicated IPs in ansible inventory
  local_action:
    module: command
    cmd: "grep -r -w {{ item }} {{ inventory_dir }}/{{ lab_name }} {{ inventory_dir }}/group_vars/nameserver.yml"
  become: false
  connection: local
  with_items: "{{ nameserver_collisions_grep.stdout_lines }}"
  when: have_collisions is defined and have_collisions|bool
  tags:
    - records
