---
# this should be a list of users in the
# following format:
# 
#   managed_users:
#     - name: username
#       key: <ssh key as a string>
#     - name: user2
#       key: <url to an ssh key>

# not given sudo access
managed_users: []
# are given sudo access
managed_admin_users: []

# A list of usernames to filter managed_users and
# managed_admin_users by.  For example, if given ['user1']
# both managed_users and managed_admin_users would be filtered
# to only contain the information for 'user1'.
users: []

# A list of users whose access is to be revoked. These accounts will be deleted.
revoked_users: []

# A repo containing SSH pubkeys. Will be used for each user that has no key
# specified.
keys_repo: "https://github.com/ceph/keys"
# Branch of above repo to use
keys_branch: main
# Where to clone keys_repo on the *local* disk
keys_repo_path: "~/.cache/src/keys"

# If the keys git repo HEAD sha1 matches the sha1 of the host's /keys-repo-sha1 file, the users role will get skipped to save time.
# Update users and pubkeys by default (this is changed to False during the play if keys_repo_head.stdout == sentinel_sha1.stdout)
perform_users_role: True
# Set this to True if you want to run the users tasks anyway
force_users_update: False
