---
mirror_host: apt-mirror.sepia.ceph.com
git_mirror_host: git.ceph.com
key_host: download.ceph.com
gitbuilder_host: gitbuilder.ceph.com
pip_mirror_url: "http://{{ mirror_host }}/pypi/simple"

# yum repos common to a major version or distro
common_yum_repos: {}

# version-specific yum repos, defined in the version specific var file
yum_repos: {}

# list of copr repo *names* to enable (e.g., user/repo)
copr_repos: []

# apt repos common to a major version or distro
common_apt_repos: []

# version-specific apt repos, defined in the the version-specific var files
apt_repos: []

# packages to install, see common_packages below as well. The set of packages to install
# is packages + common_packages
packages: []

# a list of packages that have to be installed from epel
epel_packages: []

# packages common to a major version, distro or package type. This means that they
# have the same name and are intended to be installed for all other versions in that major
# version, distro or package type
common_packages: []

# common packages that aren't available in aarch64 architecture
non_aarch64_packages: []
non_aarch64_packages_to_upgrade: []
non_aarch64_common_packages: []

# packages used by ceph we want to ensure are removed
ceph_packages_to_remove: []
ceph_dependency_packages_to_remove: []
packages_to_remove: []
packages_to_upgrade: []

# the user teuthology will use
teuthology_user: "ubuntu"
xfstests_user: "fsgqa"

# some distros need to start rpcbind before
# trying to use nfs while others don't.
start_rpcbind: true

# set to true if /etc/fstab must be modified to persist things like
# mount options, which is useful for long lived bare metal machines,
# less useful for virtual machines that are re-imaged before each job
modify_fstab: true

# used to ensure proper full and short fqdn on testnodes
lab_domain: ""

ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  - 2.us.pool.ntp.org
  - 3.us.pool.ntp.org

# Set to true in group_vars if the testnode/machine type should have an NVMe device
check_for_nvme: false

# packages to install via pip
pip_packages_to_install: []

# Configure ABRT (probably only for downstream use)
configure_abrt: false

# Configure cachefilesd (https://tracker.ceph.com/issues/6373)
configure_cachefilesd: false

# Is this a containerized testnode?
containerized_node: false
