---
ntp_service_name: ntp
ssh_service_name: ssh
nfs_service: nfs-kernel-server

packages_to_remove:
  # multipath interferes with krbd tests
  - multipath-tools
  # openmpi-common conflicts with mpich stuff
  - openmpi-common
  # tgt interferes with ceph-iscsi tests
  - tgt

ceph_packages_to_remove:
  - ceph
  - ceph-common
  - libcephfs1
  - radosgw
  - python-ceph
  - python-rados
  - python-cephfs
  - python-rbd
  - librbd1
  - librados2
  - ceph-fs-common-dbg
  - ceph-fs-common

packages: []
common_packages: []

apt_repos: []
common_apt_repos: []

# pip_packages_to_install:
#   - remoto>=0.0.35
