---
apt_repos:
  - "deb http://ceph.com/debian-dumpling/ wheezy main"
  - "deb http://gitbuilder.ceph.com/libapache-mod-fastcgi-deb-wheezy-x86_64-basic/ref/master/ wheezy main"

packages:
  - lsb-release
  - build-essential
  - sysstat
  - gdb
  - python-configobj
  - python-gevent
  - python-dev
  - python-virtualenv
  - libev-dev
  - fuse
  - libssl1.0.0
  - libgoogle-perftools4
  - libboost-thread1.49.0
  - cryptsetup-bin
  - libcrypto++9
  - iozone3
  - libmpich2-3
  - collectl
  - nfs-kernel-server
  # for running ceph
  - libedit2
  - xfsprogs
  - gdisk
  - parted
  ###
  # for setting BIOS settings 
  - libsmbios-bin
  ###
  - libuuid1
  - libfcgi
  - btrfs-tools
  # for compiling helpers and such
  - libatomic-ops-dev
  ###
  # used by workunits
  - git-core
  - attr
  - dbench
  - bonnie++
  - valgrind
  - python-nose
  - mpich2
  - libmpich2-dev
  - ant
  ###
  # used by the xfstests tasks
  - libtool
  - automake
  - gettext
  - uuid-dev
  - libacl1-dev
  - bc
  - xfsdump
  - dmapi
  - xfslibs-dev
  ###
  # For Mark Nelson
  - sysprof
  - pdsh
  ###
  # for blktrace and seekwatcher
  - blktrace
  - python-numpy
  - python-matplotlib
  - mencoder
  ###
  # for qemu
  - kvm
  - genisoimage
  ###
  # for json_xs to investigate JSON by hand
  - libjson-xs-perl
  ###
  # for pretty-printing xml
  - xml-twig-tools
  ###
  # for java bindings, hadoop, etc.
  - default-jdk
  - junit4
  ###
  # for samba testing
  - cifs-utils
  ###
  # DistCC for arm
  - distcc
  
packages_to_upgrade:
  - apt
  - libcurl3-gnutls
  - apache2
  - libapache2-mod-fastcgi
  - libfcgi0ldbl
