---
# vars specific to any rhel 8.x version

common_yum_repos:
  lab-extras:
    name: "lab-extras"
    baseurl: "http://{{ mirror_host }}/lab-extras/8/"
    enabled: 1
    gpgcheck: 0

copr_repos:
  - ceph/python3-asyncssh

packages:
  # for package-cleanup
  - dnf-utils
  - git-all
  - sysstat
  - libedit
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - fuse-libs
  - openssl
  - libuuid
  - attr
  - ant
  - lsof
  - gettext
  - bc
  - xfsdump
  - blktrace
  - usbredir
  - podman
  - redhat-lsb
  - firewalld
  - wget
  - libev-devel
  - valgrind
  - nfs-utils
  # for xfstests
  - ncurses-devel
  # for s3 tests
  # for workunits,
  - gcc
  - git
  - make
  # qa/workunits/rados/test_python.sh
  - python3-nose
  # for cram tests
  - python3-virtualenv
  # for rbd qemu tests
  - genisoimage
  - qemu-img
  - qemu-kvm-core
  - qemu-kvm-block-rbd
  # for pjd tests
  - libacl-devel
  # for fs tests,
  - autoconf
  # for test-crash.sh
  - gdb
  - iozone
  # cephadm
  - lvm2

epel_packages:
  - dbench

nfs_service: nfs-server

ntp_service_name: chronyd
