---
apt_repos:
  # http://tracker.ceph.com/issues/18126
  - "deb [trusted=yes] https://chacra.ceph.com/r/valgrind/latest/HEAD/ubuntu/xenial/flavors/default/ xenial main"

packages:
  - libboost-thread1.58.0
  - mpich
  - qemu-system-s390x
  - qemu-utils
  - python-virtualenv
  - python-configobj
  - python-gevent
  - python-numpy
  - python-matplotlib
  - python-nose
  - btrfs-tools
#  - blkin
  - lttng-tools
  ###
  # for setting BIOS settings
  ###
  - libcrypto++9v5
  ###
  # for building xfstests #18067
  - libtool-bin

packages_to_upgrade:
  # http://tracker.ceph.com/issues/13522#note-51
  # - libgoogle-perftools4
  # http://tracker.ceph.com/issues/18126#note-11
  - valgrind

non_aarch64_packages:
  # - libgoogle-perftools4
  - iozone3
  - libssl1.0.0
