---
packages:
  - mpich
  # - qemu-system-x86
  - python-virtualenv
  - python-configobj
  - python-gevent
  - python-numpy
  - python-matplotlib
  - python-nose
  - btrfs-tools
#  - blkin
  - lttng-tools
  # for building xfstests #18067
  - libtool-bin
  # for ceph-daemon (no podman on ubuntu/debian, yet)
  - docker.io
  # qa/workunits/rbd/test_librbd_python.sh
  - python3-nose

non_aarch64_packages:
  - libgoogle-perftools4
  - iozone3
  - libssl1.0.0

non_aarch64_packages_to_upgrade: []
