---
ntp_service_name: ntpd
ssh_service_name: sshd

packages_to_remove:
  # multipath interferes with krbd tests
  - device-mapper-multipath

# ceph packages that we ensure do not exist
ceph_packages_to_remove:
  - ceph
  - ceph-base
  - ceph-selinux
  - ceph-common
  - ceph-debuginfo
  - ceph-release
  - libcephfs1
  - ceph-radosgw
  - python-ceph
  - python-rados
  - python-rbd
  - python-cephfs
  - librbd1
  - librados2
  - mod_fastcgi

ceph_dependency_packages_to_remove:
  - boost-random
  - boost-program-options
  - leveldb
  - xmlstarlet
  - python-jinja2
  - python-ceph
  - python-flask
  - python-requests
  - boost-random
  - python-urllib3
  - python-babel
  - hdparm
  - python-markupsafe
  - python-werkzeug
  - python-itsdangerous

pip_packages_to_install:
  - remoto>=0.0.35

# This gets defined to "-stream" in roles/testnode/tasks/yum_systems.yml when CentOS Stream is the OS.
# It adds "-stream" to yum repo mirrorlist URLs.
dash_stream: ""
