---
rhsm_repos:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - codeready-builder-for-rhel-8-x86_64-rpms

nrpe_selinux_packages:
  - python3-libsemanage
  - python3-policycoreutils
