---
- name: Check to see if the ISO exists
  stat: path={{ iso_path }} get_checksum=no
  register: iso_stat

- name: Download ISO
  get_url:
      url={{ distro.iso }}
      dest={{ iso_path }}
      checksum=sha256:{{ distro.sha256 }}
  when: profile is defined and profile.stdout == ''
  register: download
