---
- name: Set image scratch directory
  set_fact:
    image_path: "{{ other_image_dir }}/{{ distro_name }}"

- name: Set kernel name
  set_fact:
      kernel_name: "{{ distro.kernel.split('/')[-1] }}"

- name: Set kernel path
  set_fact:
      kernel_path: "{{ other_image_dir }}/{{ kernel_name }}"

- name: Set initrd name
  set_fact:
      initrd_name: "{{ distro.initrd.split('/')[-1] }}"

- name: Set initrd path
  set_fact:
      initrd_path: "{{ other_image_dir }}/{{ initrd_name }}"

- import_tasks: download_image.yml
  when: distro.kernel != ''

- name: Set arch
  set_fact:
      arch: "{{ distro.arch|default('x86_64') }}"
  when: download_kernel is defined and download_kernel is success

- name: Add the distro to cobbler
  command: cobbler distro add --kernel {{ kernel_path }} --initrd {{ initrd_path }} --name {{ distro_name }}
  when: download is changed or (files_exist and
        profile is defined and profile.stdout == '')
  register: imported

- name: Add the profile to cobbler
  command: cobbler profile add --name {{ distro_name }} --distro {{ distro_name }}
  when: imported is defined and imported.stdout == ''
  register: imported
