---
- name: Get current value for kernel_options_post
  shell: "cobbler profile dumpvars --name={{ distro_name }} | grep '^kernel_options_post :' | cut -d : -f 2"
  changed_when: false
  register: kernel_options_post

- name: "Set the profile's kernel_options_post if needed."
  command: cobbler profile edit --name={{ distro_name }} "{{ kopts_flag }}"-post='{{ distro.kernel_options_post }}'
  when: kernel_options_post.stdout.strip() != distro.kernel_options_post
