---
- name: Set kickstart path
  set_fact:
    kickstart_path: "{{ ks_dir }}/{{ distro.kickstart }}"

- name: Check to see if the kickstart needs updating
  shell: cobbler profile dumpvars --name={{ distro_name }} | grep '^kickstart :' | awk '{ print $3 }'
  when: kickstart_path is defined
  changed_when: false
  register: kickstart

- name: "Set the profile's kickstart"
  command: cobbler profile edit --name={{ distro_name }} "{{ autoinstall_flag }}"={{ kickstart_path }}
  when: kickstart is defined and
        kickstart.stdout != kickstart_path
